# Residual Dialyzer warnings from compile-time JSON schema literals, HEEx-generated guards,
# Agent-backed debugger delegates, and third-party WebSockex option types.
# Logic is covered by tests; suppressing analyzer false positives until upstream fixes land.
[
  {"lib/ide_web/live/workspace_live/resources_page.ex", :call},
  {"lib/ide_web/live/workspace_live/editor_support.ex", :pattern_match},
  {"lib/ide/settings.ex", :pattern_match},
  {"lib/ide/debugger/pending_http_followups.ex", :unused_fun},
  {"lib/ide/debugger/pending_protocol_delivery.ex", :unused_fun},
  {"lib/ide/debugger.ex", :no_return},
  {"lib/ide/debugger/agent_hosts.ex", :no_return},
  {"lib/ide/debugger/agent_session.ex", :no_return},
  {"lib/ide/debugger/compile_ingest_api.ex", :no_return},
  {"lib/ide/debugger/configuration_api.ex", :no_return},
  {"lib/ide/debugger/runtime_api.ex", :no_return},
  {"lib/ide/debugger/runtime_api.ex", :pattern_match},
  {"lib/ide/debugger/runtime_contexts.ex", :no_return},
  {"lib/ide/debugger/runtime_hub.ex", :no_return},
  {"lib/ide/debugger/session_api.ex", :no_return},
  {"lib/ide/debugger/tick_api.ex", :no_return},
  {"lib/ide/debugger/trace_api.ex", :no_return},
  {"lib/ide/debugger/triggers_api.ex", :no_return},
  {"lib/ide/mcp/handlers/debugger.ex", :unused_fun},
  # Dialyzer reports `@moduledoc` / `@doc false` as line-1 pattern_match (false vs true).
  {"lib/ide_web/live/workspace_live/debugger_flow/core.ex", :unused_fun},
  {"lib/ide_web/live/workspace_live/debugger_flow/core.ex", :no_return},
  {"lib/ide_web/live/workspace_live/debugger_flow/core.ex", :pattern_match},
  {"lib/ide/debugger/runtime_model_normalize.ex", :pattern_match},
  {"lib/ide/mcp/handlers/compiler.ex", :pattern_match},
  {"lib/ide/mcp/handlers/debugger.ex", :pattern_match},
  {"lib/ide/debugger/runtime_hub.ex", :pattern_match},
  {"lib/ide/debugger/auto_fire_runtime.ex", :pattern_match},
  {"lib/ide/debugger/companion_phone_compile.ex", :no_return},
  {"lib/ide/debugger/deferred_companion_init.ex", :no_return},
  {"lib/ide_web/live/workspace_live/debugger_bootstrap_flow.ex", :no_return},
  {"lib/ide_web/live/workspace_live/debugger_bootstrap_flow.ex", :unused_fun},
  {"lib/ide_web/live/workspace_live/debugger_bootstrap_flow.ex", :pattern_match},
  {"lib/ide/mcp/debugger_template_corpus.ex", :pattern_match},
  {"lib/ide/mcp/debugger_template_corpus.ex", :unused_fun},
  {"lib/ide/debugger/runtime_contexts.ex", :call},
  {"lib/ide/emulator/pbw_installer/post_install.ex", :call},
  {"lib/ide/mcp/debugger_template_corpus.ex", :no_return},
  {"lib/ide_web/live/workspace_live/debugger_support/timeline/debugger_rows.ex", :invalid_contract},
  {"lib/ide_web/live/workspace_live/debugger_page/export.ex", :pattern_match},
  # Preview PNG generator calls corpus bootstrap; Dialyzer cannot prove template validation succeeds.
  {"lib/ide/project_template_previews.ex", :pattern_match},
  {"lib/ide/project_template_previews.ex", :no_return},
  {"lib/ide/project_template_previews.ex", :unused_fun},
  {"lib/ide/debugger/protocol_rx.ex", :exact_eq},
  {"lib/ide/debugger/runtime_background_drains.ex", :no_return},
  {"lib/ide/debugger/runtime_hub.ex", :unused_fun},
  {"lib/ide/debugger/session_api.ex", :pattern_match_cov},
  {"lib/ide/debugger/pending_speaker_followups.ex", :no_return},
  {"lib/ide/debugger/pending_speaker_followups.ex", :unused_fun},
  {"lib/ide/debugger/runtime_active_subscriptions.ex", :pattern_match},
  {"lib/ide/debugger/runtime_followups.ex", :pattern_match},
  {"lib/ide/debugger/trigger_surface.ex", :pattern_match},
  {"lib/ide/debugger/triggers_api.ex", :pattern_match_cov},
  {"lib/ide/debugger/device_data.ex", :pattern_match},
  # Deferred companion init runs only after parser-only bootstrap sets the defer flag.
  {"lib/ide/debugger/deferred_companion_init.ex", :unused_fun},
  # Mix task drives real templates and filesystem I/O; Dialyzer cannot prove success paths.
  {"lib/mix/tasks/ide.size_report.ex", :pattern_match},
  {"lib/mix/tasks/ide.size_report.ex", :unused_fun},
]
