defmodule Ide.GitHub.Push do
  @moduledoc """
  Pushes the IDE workspace to GitHub using a persistent mirror repository.

  Each push adds a new commit when files changed (preserving history on GitHub).
  Unchanged files keep their prior commit timestamps on the remote.
  """

  alias Ide.GitHub.Credentials
  alias Ide.GitHub.Types
  alias Ide.ProjectReadme
  alias Ide.Projects
  alias Ide.Projects.Project
  alias Ide.Projects.Types, as: ProjectsTypes

  @mirror_dir ".elm-pebble-github"

  @workspace_copy_excludes MapSet.new([
                             @mirror_dir,
                             ".git",
                             ".pebble-sdk",
                             ".elm-pebble-publish",
                             "elm-stuff",
                             "node_modules",
                             "_build",
                             "deps"
                           ])

  @push_gitignore """
  # Generated by Elm Pebble IDE — excluded from GitHub pushes
  .pebble-sdk/
  .elm-pebble-publish/
  .elm-pebble-github/
  elm-stuff/
  node_modules/
  _build/
  deps/
  """

  @spec push_project_snapshot(Project.t(), ProjectsTypes.github_config(), keyword()) ::
          {:ok, Types.push_snapshot_result()} | {:error, Types.push_error()}
  def push_project_snapshot(%Project{} = project, repo_config, opts \\ []) do
    with {:ok, project} <- Projects.ensure_app_uuid(project),
         {:ok, token} <- fetch_access_token(),
         {:ok, owner} <- fetch_repo_value(repo_config, "owner"),
         {:ok, repo} <- fetch_repo_value(repo_config, "repo"),
         branch <- fetch_branch(repo_config),
         workspace_root <- Projects.project_workspace_path(project),
         {:ok, mirror_root} <- mirror_root(workspace_root),
         :ok <- File.mkdir_p(mirror_root),
         :ok <- ensure_mirror_repo(mirror_root, branch),
         :ok <- sync_workspace_to_mirror(workspace_root, mirror_root),
         :ok <- ProjectReadme.write(mirror_root, project),
         :ok <- write_push_gitignore(mirror_root),
         {:ok, committed} <- commit_if_changed(mirror_root, opts),
         :ok <- ensure_remote(mirror_root, token, owner, repo),
         :ok <- integrate_remote(mirror_root, branch),
         :ok <- push_branch(mirror_root, branch),
         {:ok, commit_sha} <- read_commit_sha(mirror_root) do
      {:ok,
       %{
         branch: branch,
         owner: owner,
         repo: repo,
         commit_sha: commit_sha,
         remote_url: "https://github.com/#{owner}/#{repo}",
         committed: committed,
         history_replaced: false
       }}
    end
  end

  @spec mirror_dir() :: String.t()
  def mirror_dir, do: @mirror_dir

  @spec mirror_root(String.t()) :: {:ok, String.t()}
  defp mirror_root(workspace_root), do: {:ok, Path.join(workspace_root, @mirror_dir)}

  @spec fetch_access_token() :: {:ok, String.t()} | {:error, :github_not_connected}
  defp fetch_access_token do
    case Credentials.access_token() do
      token when is_binary(token) and token != "" -> {:ok, token}
      _ -> {:error, :github_not_connected}
    end
  end

  @spec fetch_repo_value(ProjectsTypes.github_config(), String.t()) ::
          {:ok, String.t()} | {:error, Types.repo_field_error()}
  defp fetch_repo_value(map, key) when is_map(map) do
    value = Map.get(map, key) || Map.get(map, String.to_atom(key))

    case value do
      str when is_binary(str) ->
        trimmed = String.trim(str)
        if trimmed == "", do: {:error, {:missing_repo_field, key}}, else: {:ok, trimmed}

      _ ->
        {:error, {:missing_repo_field, key}}
    end
  end

  defp fetch_repo_value(_map, key), do: {:error, {:missing_repo_field, key}}

  @spec fetch_branch(ProjectsTypes.github_config()) :: String.t()
  defp fetch_branch(map) when is_map(map) do
    branch = Map.get(map, "branch") || Map.get(map, :branch) || "main"
    trimmed = if is_binary(branch), do: String.trim(branch), else: ""
    if trimmed == "", do: "main", else: trimmed
  end

  @spec ensure_mirror_repo(String.t(), String.t()) :: :ok | {:error, Types.push_error()}
  defp ensure_mirror_repo(mirror_root, branch) do
    git_dir = Path.join(mirror_root, ".git")

    if File.dir?(git_dir) do
      run_git(mirror_root, ["checkout", "-B", branch])
    else
      with :ok <- run_git(mirror_root, ["init"]),
           :ok <- run_git(mirror_root, ["checkout", "-B", branch]) do
        :ok
      end
    end
  end

  @spec sync_workspace_to_mirror(String.t(), String.t()) :: :ok | {:error, Types.push_error()}
  defp sync_workspace_to_mirror(workspace_root, mirror_root) do
    with :ok <- clean_mirror_worktree(mirror_root),
         :ok <- copy_workspace_entries(workspace_root, mirror_root) do
      :ok
    end
  end

  @spec clean_mirror_worktree(String.t()) :: :ok | {:error, Types.push_error()}
  defp clean_mirror_worktree(mirror_root) do
    case File.ls(mirror_root) do
      {:ok, entries} ->
        entries
        |> Enum.reject(&(&1 == ".git"))
        |> Enum.reduce(:ok, fn entry, acc ->
          if acc == :ok, do: rm_rf(Path.join(mirror_root, entry)), else: acc
        end)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp rm_rf(path) do
    case File.rm_rf(path) do
      {:ok, _} -> :ok
      {:error, reason, _} -> {:error, reason}
    end
  end

  @spec copy_workspace_entries(String.t(), String.t()) :: :ok | {:error, Types.push_error()}
  defp copy_workspace_entries(workspace_root, mirror_root) do
    case File.ls(workspace_root) do
      {:ok, entries} ->
        entries
        |> Enum.reject(&MapSet.member?(@workspace_copy_excludes, &1))
        |> Enum.reduce(:ok, fn entry, acc ->
          if acc == :ok,
            do: copy_entry(Path.join(workspace_root, entry), Path.join(mirror_root, entry)),
            else: acc
        end)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp copy_entry(source, dest) do
    case File.lstat(source) do
      {:ok, %{type: :directory}} ->
        case File.cp_r(source, dest) do
          {:ok, _} -> :ok
          {:error, reason, _} -> {:error, reason}
        end

      {:ok, %{type: :regular}} ->
        File.mkdir_p!(Path.dirname(dest))
        File.cp(source, dest)

      {:ok, %{type: :symlink}} ->
        :ok

      {:error, reason} ->
        {:error, reason}
    end
  end

  @spec write_push_gitignore(String.t()) :: :ok | {:error, Types.push_error()}
  defp write_push_gitignore(target_root) do
    File.write(Path.join(target_root, ".gitignore"), @push_gitignore)
  end

  @spec commit_if_changed(String.t(), keyword()) ::
          {:ok, boolean()} | {:error, Types.push_error()}
  defp commit_if_changed(path, opts) do
    message = Keyword.get(opts, :commit_message, "Update from Elm Pebble IDE")

    with :ok <- run_git(path, ["add", "-A"]),
         {:ok, has_changes} <- staged_changes?(path) do
      if has_changes do
        case run_git(path, ["commit", "-m", message], env: commit_env()) do
          :ok -> {:ok, true}
          error -> error
        end
      else
        {:ok, false}
      end
    end
  end

  @spec staged_changes?(String.t()) :: {:ok, boolean()} | {:error, Types.git_error()}
  defp staged_changes?(path) do
    case System.cmd("git", ["diff", "--cached", "--quiet"], cd: path, stderr_to_stdout: true) do
      {_, 0} -> {:ok, false}
      {_, 1} -> {:ok, true}
      {output, _} -> {:error, {:git_failed, "diff --cached --quiet", String.trim(output)}}
    end
  end

  @spec ensure_remote(String.t(), String.t(), String.t(), String.t()) ::
          :ok | {:error, Types.push_error()}
  defp ensure_remote(path, token, owner, repo) do
    remote_url =
      "https://x-access-token:#{URI.encode_www_form(token)}@github.com/#{owner}/#{repo}.git"

    case run_git(path, ["remote", "get-url", "origin"]) do
      :ok ->
        run_git(path, ["remote", "set-url", "origin", remote_url])

      {:error, _} ->
        run_git(path, ["remote", "add", "origin", remote_url])
    end
  end

  @spec integrate_remote(String.t(), String.t()) :: :ok | {:error, Types.push_error()}
  defp integrate_remote(path, branch) do
    case run_git(path, ["fetch", "origin", branch]) do
      :ok -> merge_fetched_remote(path, branch)
      {:error, _} -> :ok
    end
  end

  @spec merge_fetched_remote(String.t(), String.t()) :: :ok | {:error, Types.push_error()}
  defp merge_fetched_remote(path, branch) do
    remote_ref = "origin/#{branch}"

    case run_git(path, ["rev-parse", "--verify", remote_ref]) do
      :ok ->
        case run_git(path, ["merge", remote_ref, "--no-edit"]) do
          :ok ->
            :ok

          {:error, _} ->
            run_git(path, [
              "merge",
              remote_ref,
              "--allow-unrelated-histories",
              "--no-edit",
              "-X",
              "ours"
            ])
        end

      {:error, _} ->
        :ok
    end
  end

  @spec push_branch(String.t(), String.t()) :: :ok | {:error, Types.push_error()}
  defp push_branch(path, branch) do
    case run_git(path, ["push", "-u", "origin", branch]) do
      :ok ->
        :ok

      {:error, {:git_failed, _command, output}} ->
        {:error, {:push_rejected, output}}
    end
  end

  @spec read_commit_sha(String.t()) :: {:ok, String.t()} | {:error, Types.git_error()}
  defp read_commit_sha(path) do
    case System.cmd("git", ["rev-parse", "HEAD"], cd: path, stderr_to_stdout: true) do
      {sha, 0} -> {:ok, String.trim(sha)}
      {output, _} -> {:error, {:git_failed, "rev-parse HEAD", String.trim(output)}}
    end
  end

  defp commit_env do
    [
      {"GIT_AUTHOR_NAME", "Elm Pebble IDE"},
      {"GIT_AUTHOR_EMAIL", "ide@elm-pebble.local"},
      {"GIT_COMMITTER_NAME", "Elm Pebble IDE"},
      {"GIT_COMMITTER_EMAIL", "ide@elm-pebble.local"}
    ]
  end

  @doc false
  @spec mirror_write_readme_and_commit(String.t(), Project.t(), keyword()) ::
          {:ok, boolean()} | {:error, Types.push_error()}
  def mirror_write_readme_and_commit(mirror_root, %Project{} = project, opts \\ []) do
    with :ok <- ProjectReadme.write(mirror_root, project),
         {:ok, committed} <- commit_if_changed(mirror_root, opts) do
      {:ok, committed}
    end
  end

  @doc false
  @spec mirror_sync_and_commit(String.t(), keyword()) ::
          {:ok, String.t(), boolean()} | {:error, Types.push_error()}
  def mirror_sync_and_commit(workspace_root, opts \\ []) when is_binary(workspace_root) do
    branch = Keyword.get(opts, :branch, "main")

    with {:ok, mirror_root} <- mirror_root(workspace_root),
         :ok <- File.mkdir_p(mirror_root),
         :ok <- ensure_mirror_repo(mirror_root, branch),
         :ok <- sync_workspace_to_mirror(workspace_root, mirror_root),
         :ok <- write_push_gitignore(mirror_root),
         {:ok, committed} <- commit_if_changed(mirror_root, opts) do
      {:ok, mirror_root, committed}
    end
  end

  @spec run_git(String.t(), [String.t()], keyword()) :: :ok | {:error, Types.git_error()}
  defp run_git(path, args, opts \\ []) do
    cmd_opts =
      [cd: path, stderr_to_stdout: true]
      |> Keyword.merge(opts)

    case System.cmd("git", args, cmd_opts) do
      {_output, 0} ->
        :ok

      {output, _status} ->
        {:error, {:git_failed, Enum.join(args, " "), String.trim(output)}}
    end
  end
end
