[
  {"lib/elm_ex/ir/function_call_check.ex", :pattern_match_cov},
  {"lib/elm_ex/ir/function_call_check.ex", :invalid_contract},
  {"lib/elm_ex/ir/function_call_check.ex", :unused_fun},
  {"lib/elm_ex/ir/function_call_check.ex", :no_return},
  {"lib/elm_ex/ir/function_call_check.ex", :call},
  {"lib/elm_ex/frontend/bridge.ex", :pattern_match_cov},
  {"lib/elm_ex/frontend/generated_expression_parser.ex", :guard_fail},
  {"lib/elm_ex/debugger_contract/effect_analysis.ex", :guard_fail},
  {"lib/elm_ex/debugger_contract/effect_analysis/support.ex", :guard_fail},
  {"lib/elm_ex/debugger_contract/effect_analysis/support.ex", :unused_fun},
  {"lib/elm_ex/debugger_contract/view_tree/structure.ex", :pattern_match},
  {"lib/elm_ex/ir/lowerer.ex", :invalid_contract},
  {"lib/elm_ex/ir/lowerer.ex", :unused_fun},
  {"lib/elm_ex/ir/lowerer.ex", :no_return},
  {"lib/elm_ex/ir/lowerer.ex", :call},
]
