(module
  (import "runtime" "as_int" (func $runtime_as_int (param i32) (result i32)))
  (import "runtime" "browser_cmd" (func $runtime_browser_cmd (param i32 i32 i32) (result i32)))
  (import "runtime" "call_closure" (func $runtime_call_closure (param i32 i32 i32 i32) (result i32)))
  (import "runtime" "html_cmd" (func $runtime_html_cmd (param i32 i32 i32 i32 i32) (result i32)))
  (import "runtime" "list_from_values" (func $runtime_list_from_values (param i32 i32 i32) (result i32)))
  (import "runtime" "list_nil" (func $runtime_list_nil (param i32) (result i32)))
  (import "runtime" "make_closure" (func $runtime_make_closure (param i32 i32 i32 i32) (result i32)))
  (import "runtime" "new_immortal_string" (func $runtime_new_immortal_string (param i32 i32) (result i32)))
  (import "runtime" "new_int" (func $runtime_new_int (param i32 i32) (result i32)))
  (import "runtime" "record_get" (func $runtime_record_get (param i32 i32 i32) (result i32)))
  (import "runtime" "record_new" (func $runtime_record_new (param i32 i32 i32 i32 i32) (result i32)))
  (import "runtime" "release" (func $runtime_release (param i32) (result i32)))
  (import "runtime" "release_array_lifo" (func $runtime_release_array_lifo (param i32 i32) (result i32)))
  (import "runtime" "retain" (func $runtime_retain (param i32 i32) (result i32)))
  (import "runtime" "tuple2" (func $runtime_tuple2 (param i32 i32 i32) (result i32)))
  (import "runtime" "unit" (func $runtime_unit (param i32) (result i32)))
  (memory (export "memory") 1)
  (func $elmc_fn_Browser_sandbox (export "elmc_fn_Browser_sandbox") (param $param0 i32) (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned3 i32)
  (local $owned4 i32)
  (local $owned5 i32)
  (local $owned6 i32)
  (local $owned7 i32)
  (local $reg0 i32)
  (local $reg1 i32)
  (local $reg2 i32)
  (local $reg3 i32)
  (local $reg4 i32)
  (local $reg5 i32)
  (local $reg6 i32)
  (local $reg7 i32)
  (local.set $rc (i32.const 0))
  (local.set $reg0 (local.get $param0))
  (call $runtime_retain (i32.const 1052) (local.get $reg0))
  (local.set $reg1 (i32.load  offset=1052 (i32.const 0)))
  (if (i32.ne  (local.get $owned4) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned4)))))
  (local.set $owned4 (local.get $reg1))
  (call $runtime_make_closure (i32.const 1056) (i32.const 0) (i32.const 1) (local.get $reg1))
  (local.set $reg2 (i32.load  offset=1056 (i32.const 0)))
  (if (i32.ne  (local.get $owned5) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned5)))))
  (local.set $owned5 (local.get $reg2))
  (call $runtime_make_closure (i32.const 1060) (i32.const 1) (i32.const 1) (i32.const 0))
  (local.set $reg3 (i32.load  offset=1060 (i32.const 0)))
  (if (i32.ne  (local.get $owned4) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned4)))))
  (local.set $owned4 (local.get $reg3))
  (call $runtime_retain (i32.const 1064) (local.get $reg0))
  (local.set $reg4 (i32.load  offset=1064 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg4))
  (call $runtime_make_closure (i32.const 1068) (i32.const 2) (i32.const 2) (local.get $reg4))
  (local.set $reg5 (i32.load  offset=1068 (i32.const 0)))
  (if (i32.ne  (local.get $owned7) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned7)))))
  (local.set $owned7 (local.get $reg5))
  (call $runtime_record_get (i32.const 1072) (local.get $reg0) (i32.const 0))
  (local.set $reg6 (i32.load  offset=1072 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg6))
  (call $runtime_record_new (i32.const 1076) (local.get $reg2) (local.get $reg3) (local.get $reg5) (local.get $reg6))
  (local.set $reg7 (i32.load  offset=1076 (i32.const 0)))
  (if (i32.ne  (local.get $owned3) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned3)))))
  (local.set $owned3 (local.get $reg7))
  (call $runtime_browser_cmd (i32.const 1024) (i32.const 6) (local.get $reg7))
  (local.set $fn_out (i32.load  offset=1024 (i32.const 0)))
  (if (i32.and  (i32.ne  (local.get $owned7) (i32.const 0)) (i32.ne  (local.get $owned7) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned7)))))
  (if (i32.and  (i32.ne  (local.get $owned6) (i32.const 0)) (i32.ne  (local.get $owned6) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned6)))))
  (if (i32.and  (i32.ne  (local.get $owned5) (i32.const 0)) (i32.ne  (local.get $owned5) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned5)))))
  (if (i32.and  (i32.ne  (local.get $owned4) (i32.const 0)) (i32.ne  (local.get $owned4) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned4)))))
  (if (i32.and  (i32.ne  (local.get $owned3) (i32.const 0)) (i32.ne  (local.get $owned3) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned3)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Html_div (export "elmc_fn_Html_div")  (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned2 i32)
  (local $reg0 i32)
  (local.set $rc (i32.const 0))
  (call $runtime_new_immortal_string (i32.const 1032) (i32.const 28402))
  (local.set $reg0 (i32.load  offset=1032 (i32.const 0)))
  (if (i32.ne  (local.get $owned2) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned2)))))
  (local.set $owned2 (local.get $reg0))
  (call $runtime_html_cmd (i32.const 1024) (i32.const 2) (local.get $reg0) (i32.const 0) (i32.const 0))
  (local.set $fn_out (i32.load  offset=1024 (i32.const 0)))
  (if (i32.and  (i32.ne  (local.get $owned2) (i32.const 0)) (i32.ne  (local.get $owned2) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned2)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Html_text (export "elmc_fn_Html_text")  (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local.set $rc (i32.const 0))
  (call $runtime_html_cmd (i32.const 1024) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 0))
  (local.set $fn_out (i32.load  offset=1024 (i32.const 0)))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Main_main (export "elmc_fn_Main_main")  (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned2 i32)
  (local $owned3 i32)
  (local $owned4 i32)
  (local $owned5 i32)
  (local $reg0 i32)
  (local $reg1 i32)
  (local $reg2 i32)
  (local $reg3 i32)
  (local.set $rc (i32.const 0))
  (call $runtime_unit (i32.const 1044))
  (local.set $reg0 (i32.load  offset=1044 (i32.const 0)))
  (if (i32.ne  (local.get $owned2) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned2)))))
  (local.set $owned2 (local.get $reg0))
  (call $runtime_make_closure (i32.const 1048) (i32.const 3) (i32.const 2) (i32.const 0))
  (local.set $reg1 (i32.load  offset=1048 (i32.const 0)))
  (if (i32.ne  (local.get $owned3) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned3)))))
  (local.set $owned3 (local.get $reg1))
  (call $runtime_make_closure (i32.const 1052) (i32.const 4) (i32.const 1) (i32.const 0))
  (local.set $reg2 (i32.load  offset=1052 (i32.const 0)))
  (if (i32.ne  (local.get $owned4) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned4)))))
  (local.set $owned4 (local.get $reg2))
  (call $runtime_record_new (i32.const 1056) (local.get $reg0) (local.get $reg1) (local.get $reg2) (i32.const 0))
  (local.set $reg3 (i32.load  offset=1056 (i32.const 0)))
  (if (i32.ne  (local.get $owned5) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned5)))))
  (local.set $owned5 (local.get $reg3))
  (call $elmc_fn_Browser_sandbox (local.get $reg3))
  (local.set $fn_out)
  (local.set $rc)
  (if (i32.and  (i32.ne  (local.get $owned5) (i32.const 0)) (i32.ne  (local.get $owned5) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned5)))))
  (if (i32.and  (i32.ne  (local.get $owned4) (i32.const 0)) (i32.ne  (local.get $owned4) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned4)))))
  (if (i32.and  (i32.ne  (local.get $owned3) (i32.const 0)) (i32.ne  (local.get $owned3) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned3)))))
  (if (i32.and  (i32.ne  (local.get $owned2) (i32.const 0)) (i32.ne  (local.get $owned2) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned2)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_VirtualDom_text (export "elmc_fn_VirtualDom_text")  (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local.set $rc (i32.const 0))
  (call $runtime_html_cmd (i32.const 1024) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 0))
  (local.set $fn_out (i32.load  offset=1024 (i32.const 0)))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Browser_sandbox_closure_0 (export "elmc_fn_Browser_sandbox_closure_0") (param $param0 i32) (param $param1 i32) (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned4 i32)
  (local $owned5 i32)
  (local $owned6 i32)
  (local $reg0 i32)
  (local $reg1 i32)
  (local $reg2 i32)
  (local $reg3 i32)
  (local.set $rc (i32.const 0))
  (local.set $reg0 (local.get $param0))
  (call $runtime_record_get (i32.const 1044) (local.get $reg0) (i32.const 0))
  (local.set $reg1 (i32.load  offset=1044 (i32.const 0)))
  (if (i32.ne  (local.get $owned5) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned5)))))
  (local.set $owned5 (local.get $reg1))
  ;; unsupported platform op pebble_cmd
  (call $runtime_tuple2 (i32.const 1052) (local.get $reg1) (local.get $reg2))
  (local.set $reg3 (i32.load  offset=1052 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg3))
  (local.set $fn_out (local.get $reg3))
  (if (i32.and  (i32.ne  (local.get $owned6) (i32.const 0)) (i32.ne  (local.get $owned6) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned6)))))
  (if (i32.and  (i32.ne  (local.get $owned5) (i32.const 0)) (i32.ne  (local.get $owned5) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned5)))))
  (if (i32.and  (i32.ne  (local.get $owned4) (i32.const 0)) (i32.ne  (local.get $owned4) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned4)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Browser_sandbox_closure_1 (export "elmc_fn_Browser_sandbox_closure_1") (param $param0 i32) (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned3 i32)
  (local $reg0 i32)
  (local.set $rc (i32.const 0))
  ;; unsupported platform op pebble_sub
  (local.set $fn_out (local.get $reg0))
  (if (i32.and  (i32.ne  (local.get $owned3) (i32.const 0)) (i32.ne  (local.get $owned3) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned3)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Browser_sandbox_closure_2 (export "elmc_fn_Browser_sandbox_closure_2") (param $param0 i32) (param $param1 i32) (param $param2 i32) (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned5 i32)
  (local $owned6 i32)
  (local $owned7 i32)
  (local $owned8 i32)
  (local $reg0 i32)
  (local $reg1 i32)
  (local $reg2 i32)
  (local $reg3 i32)
  (local $reg4 i32)
  (local $reg5 i32)
  (local $reg6 i32)
  (local.set $rc (i32.const 0))
  (local.set $reg0 (local.get $param0))
  (call $runtime_record_get (i32.const 1048) (local.get $reg0) (i32.const 0))
  (local.set $reg1 (i32.load  offset=1048 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg1))
  (local.set $reg2 (local.get $param1))
  (local.set $reg3 (local.get $param2))
  (call $runtime_call_closure (i32.const 1060) (local.get $reg1) (local.get $reg2) (local.get $reg3))
  (local.set $reg4 (i32.load  offset=1060 (i32.const 0)))
  (if (i32.ne  (local.get $owned8) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned8)))))
  (local.set $owned8 (local.get $reg4))
  ;; unsupported platform op pebble_cmd
  (call $runtime_tuple2 (i32.const 1068) (local.get $reg4) (local.get $reg5))
  (local.set $reg6 (i32.load  offset=1068 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg6))
  (local.set $fn_out (local.get $reg6))
  (if (i32.and  (i32.ne  (local.get $owned8) (i32.const 0)) (i32.ne  (local.get $owned8) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned8)))))
  (if (i32.and  (i32.ne  (local.get $owned7) (i32.const 0)) (i32.ne  (local.get $owned7) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned7)))))
  (if (i32.and  (i32.ne  (local.get $owned6) (i32.const 0)) (i32.ne  (local.get $owned6) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned6)))))
  (if (i32.and  (i32.ne  (local.get $owned5) (i32.const 0)) (i32.ne  (local.get $owned5) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned5)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Main_main_closure_0 (export "elmc_fn_Main_main_closure_0") (param $param0 i32) (param $param1 i32) (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned4 i32)
  (local $reg0 i32)
  (local $reg1 i32)
  (local.set $rc (i32.const 0))
  (local.set $reg0 (local.get $param1))
  (local.set $fn_out (local.get $reg0))
  (if (i32.and  (i32.ne  (local.get $owned4) (i32.const 0)) (i32.ne  (local.get $owned4) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned4)))))
  (return  (local.get $rc) (local.get $fn_out))
)
  (func $elmc_fn_Main_main_closure_1 (export "elmc_fn_Main_main_closure_1") (param $param0 i32) (result i32 i32)
  (local $rc i32)
  (local $fn_out i32)
  (local $owned3 i32)
  (local $owned4 i32)
  (local $owned5 i32)
  (local $owned6 i32)
  (local $reg0 i32)
  (local $reg1 i32)
  (local $reg2 i32)
  (local $reg3 i32)
  (local $reg4 i32)
  (local $reg5 i32)
  (local.set $rc (i32.const 0))
  (call $runtime_new_immortal_string (i32.const 1044) (i32.const 28402))
  (local.set $reg0 (i32.load  offset=1044 (i32.const 0)))
  (if (i32.ne  (local.get $owned3) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned3)))))
  (local.set $owned3 (local.get $reg0))
  (call $runtime_list_nil (i32.const 1048))
  (local.set $reg1 (i32.load  offset=1048 (i32.const 0)))
  (if (i32.ne  (local.get $owned4) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned4)))))
  (local.set $owned4 (local.get $reg1))
  (call $runtime_new_immortal_string (i32.const 1052) (i32.const 494666))
  (local.set $reg2 (i32.load  offset=1052 (i32.const 0)))
  (if (i32.ne  (local.get $owned5) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned5)))))
  (local.set $owned5 (local.get $reg2))
  (call $runtime_html_cmd (i32.const 1056) (i32.const 1) (local.get $reg2) (i32.const 0) (i32.const 0))
  (local.set $reg3 (i32.load  offset=1056 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg3))
  (i32.store  offset=4096 (i32.const 0) (local.get $reg3))
  (call $runtime_list_from_values (i32.const 1060) (i32.const 4096) (i32.const 1))
  (local.set $reg4 (i32.load  offset=1060 (i32.const 0)))
  (if (i32.ne  (local.get $owned5) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned5)))))
  (local.set $owned5 (local.get $reg4))
  (call $runtime_html_cmd (i32.const 1064) (i32.const 2) (local.get $reg0) (local.get $reg1) (local.get $reg4))
  (local.set $reg5 (i32.load  offset=1064 (i32.const 0)))
  (if (i32.ne  (local.get $owned6) (i32.const 0)) (then (drop  (call $runtime_release (local.get $owned6)))))
  (local.set $owned6 (local.get $reg5))
  (local.set $fn_out (local.get $reg5))
  (if (i32.and  (i32.ne  (local.get $owned6) (i32.const 0)) (i32.ne  (local.get $owned6) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned6)))))
  (if (i32.and  (i32.ne  (local.get $owned5) (i32.const 0)) (i32.ne  (local.get $owned5) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned5)))))
  (if (i32.and  (i32.ne  (local.get $owned4) (i32.const 0)) (i32.ne  (local.get $owned4) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned4)))))
  (if (i32.and  (i32.ne  (local.get $owned3) (i32.const 0)) (i32.ne  (local.get $owned3) (local.get $fn_out))) (then (drop  (call $runtime_release (local.get $owned3)))))
  (return  (local.get $rc) (local.get $fn_out))
)
)