defmodule Elmc.Backend.Pebble.Types do
  @moduledoc false

  alias Elmc.Backend.Pebble.Types.{Bindings, Core, FeatureFlags}

  @type draw_kind :: Core.draw_kind()
  @type command_kind :: Core.command_kind()
  @type run_mode :: Core.run_mode()
  @type button_id :: Core.button_id()
  @type accel_axis :: Core.accel_axis()
  @type ui_node_kind :: Core.ui_node_kind()

  @type c_source :: Core.c_source()
  @type c_macro_name :: Core.c_macro_name()
  @type c_symbol :: Core.c_symbol()
  @type c_type_name :: Core.c_type_name()
  @type call_target :: Core.call_target()
  @type call_target_list :: Core.call_target_list()
  @type call_target_set :: Core.call_target_set()
  @type kind_table :: Core.kind_table()
  @type draw_kind_table :: Core.draw_kind_table()
  @type command_kind_table :: Core.command_kind_table()
  @type run_mode_table :: Core.run_mode_table()
  @type button_id_table :: Core.button_id_table()
  @type accel_axis_table :: Core.accel_axis_table()
  @type ui_node_kind_table :: Core.ui_node_kind_table()

  @type msg_constructor_pair :: Core.msg_constructor_pair()
  @type msg_constructor_list :: Core.msg_constructor_list()
  @type msg_constructor_name :: Core.msg_constructor_name()
  @type union_module :: Core.union_module()
  @type decl_name :: Core.decl_name()
  @type msg_constructor_arities :: Core.msg_constructor_arities()
  @type msg_constructor_payload_specs :: Core.msg_constructor_payload_specs()
  @type msg_tag :: Core.msg_tag()
  @type pick_tag_opts :: Core.pick_tag_opts()
  @type entry_module :: Core.entry_module()
  @type entry_lifecycle_fn :: Core.entry_lifecycle_fn()
  @type reachability_function_entry :: Core.reachability_function_entry()
  @type reachability_function_map :: Core.reachability_function_map()
  @type msg_union :: Core.msg_union()
  @type record_literal_bindings :: Core.record_literal_bindings()
  @type accel_config :: Core.accel_config()
  @type random_callback_candidate :: Core.random_callback_candidate()
  @type ir_walk_node :: Core.ir_walk_node()
  @type ir_map_node :: Core.ir_map_node()

  @type header_msg_macros :: Bindings.header_msg_macros()
  @type msg_fragments :: Bindings.msg_fragments()
  @type event_dispatch_bindings :: Bindings.event_dispatch_bindings()
  @type source_bindings :: Bindings.source_bindings()
  @type header_bindings :: Bindings.header_bindings()
  @type header_app_types_bindings :: Bindings.header_app_types_bindings()
  @type scene_build_bindings :: Bindings.scene_build_bindings()
  @type view_command_bindings :: Bindings.view_command_bindings()
  @type app_lifecycle_bindings :: Bindings.app_lifecycle_bindings()
  @type shim_analysis :: Bindings.shim_analysis()

  @type feature_flag :: FeatureFlags.feature_flag()
  @type feature_flag_key :: FeatureFlags.feature_flag_key()
  @type command_feature_flags :: FeatureFlags.command_feature_flags()
  @type command_storage_flags :: FeatureFlags.command_storage_flags()
  @type command_timer_wakeup_flags :: FeatureFlags.command_timer_wakeup_flags()
  @type command_backlight_flags :: FeatureFlags.command_backlight_flags()
  @type command_time_timezone_flags :: FeatureFlags.command_time_timezone_flags()
  @type command_device_query_flags :: FeatureFlags.command_device_query_flags()
  @type command_logging_flags :: FeatureFlags.command_logging_flags()
  @type command_system_flags :: FeatureFlags.command_system_flags()
  @type command_vibes_flags :: FeatureFlags.command_vibes_flags()
  @type command_health_flags :: FeatureFlags.command_health_flags()
  @type command_device_services_flags :: FeatureFlags.command_device_services_flags()
  @type command_speaker_flags :: FeatureFlags.command_speaker_flags()
  @type command_services_flags :: FeatureFlags.command_services_flags()
  @type draw_feature_flags :: FeatureFlags.draw_feature_flags()
  @type draw_primitive_flags :: FeatureFlags.draw_primitive_flags()
  @type draw_context_flags :: FeatureFlags.draw_context_flags()
  @type draw_text_flags :: FeatureFlags.draw_text_flags()
  @type event_feature_flags :: FeatureFlags.event_feature_flags()
  @type event_clock_flags :: FeatureFlags.event_clock_flags()
  @type event_input_flags :: FeatureFlags.event_input_flags()
  @type event_constructor_platform_flags :: FeatureFlags.event_constructor_platform_flags()
  @type event_subscription_platform_flags :: FeatureFlags.event_subscription_platform_flags()
  @type event_platform_flags :: FeatureFlags.event_platform_flags()
  @type compass_dispatch_flags :: FeatureFlags.compass_dispatch_flags()
  @type feature_flags :: FeatureFlags.feature_flags()
end
