defmodule Elmc.Backend.CCodegen.Constants do
  @moduledoc false

  @pebble_color_constants %{
    "clearColor" => 0x00,
    "black" => 0xC0,
    "oxfordBlue" => 0xC1,
    "dukeBlue" => 0xC2,
    "blue" => 0xC3,
    "darkGreen" => 0xC4,
    "midnightGreen" => 0xC5,
    "cobaltBlue" => 0xC6,
    "blueMoon" => 0xC7,
    "islamicGreen" => 0xC8,
    "jaegerGreen" => 0xC9,
    "tiffanyBlue" => 0xCA,
    "vividCerulean" => 0xCB,
    "green" => 0xCC,
    "malachite" => 0xCD,
    "mediumSpringGreen" => 0xCE,
    "cyan" => 0xCF,
    "bulgarianRose" => 0xD0,
    "imperialPurple" => 0xD1,
    "indigo" => 0xD2,
    "electricUltramarine" => 0xD3,
    "armyGreen" => 0xD4,
    "darkGray" => 0xD5,
    "liberty" => 0xD6,
    "veryLightBlue" => 0xD7,
    "kellyGreen" => 0xD8,
    "mayGreen" => 0xD9,
    "cadetBlue" => 0xDA,
    "pictonBlue" => 0xDB,
    "brightGreen" => 0xDC,
    "screaminGreen" => 0xDD,
    "mediumAquamarine" => 0xDE,
    "electricBlue" => 0xDF,
    "darkCandyAppleRed" => 0xE0,
    "jazzberryJam" => 0xE1,
    "purple" => 0xE2,
    "vividViolet" => 0xE3,
    "windsorTan" => 0xE4,
    "roseVale" => 0xE5,
    "purpureus" => 0xE6,
    "lavenderIndigo" => 0xE7,
    "limerick" => 0xE8,
    "brass" => 0xE9,
    "lightGray" => 0xEA,
    "babyBlueEyes" => 0xEB,
    "springBud" => 0xEC,
    "inchworm" => 0xED,
    "mintGreen" => 0xEE,
    "celeste" => 0xEF,
    "red" => 0xF0,
    "folly" => 0xF1,
    "fashionMagenta" => 0xF2,
    "magenta" => 0xF3,
    "orange" => 0xF4,
    "sunsetOrange" => 0xF5,
    "brilliantRose" => 0xF6,
    "shockingPink" => 0xF7,
    "chromeYellow" => 0xF8,
    "rajah" => 0xF9,
    "melon" => 0xFA,
    "richBrilliantLavender" => 0xFB,
    "yellow" => 0xFC,
    "icterine" => 0xFD,
    "pastelYellow" => 0xFE,
    "white" => 0xFF
  }

  @spec pebble_color_constants() :: %{String.t() => integer()}
  def pebble_color_constants, do: @pebble_color_constants
end
