defmodule IdeWeb.WorkspaceLive.SocketAssigns do
  @moduledoc """
  Full workspace LiveView socket assigns for `IdeWeb.WorkspaceLive`.

  Pane `*Page.Assigns` modules alias this type because each pane `render/1` receives
  the whole workspace socket.
  """

  alias Ide.Auth
  alias Ide.Auth.Types, as: AuthTypes
  alias Ide.Compiler
  alias Ide.Debugger.Types, as: DebuggerTypes
  alias Ide.EditorCompletion.Types, as: CompletionTypes
  alias Ide.Emulator.Types, as: EmulatorTypes
  alias Ide.GitHub.Repositories
  alias Ide.Projects.FileTypes
  alias Ide.Projects.Project
  alias Ide.Packages.Types, as: PackageTypes
  alias Ide.PublishReadiness
  alias Ide.Resources.Types, as: ResourceTypes
  alias Ide.Screenshots
  alias Ide.Settings
  alias Ide.StoreAssets
  alias Ide.Auth.User
  alias IdeWeb.LiveView.Assigns, as: LiveViewAssigns
  alias IdeWeb.WorkspaceLive.BuildFlow
  alias IdeWeb.WorkspaceLive.DebuggerFlow.Types, as: FlowTypes
  alias IdeWeb.WorkspaceLive.DebuggerPage.CompanionConfiguration
  alias IdeWeb.WorkspaceLive.DebuggerSupport.Types, as: SupportTypes
  alias IdeWeb.WorkspaceLive.EditorDependencies
  alias IdeWeb.WorkspaceLive.EditorSupport.Types, as: EditorTypes
  alias IdeWeb.WorkspaceLive.ProjectSettingsFlow
  alias IdeWeb.WorkspaceLive.PublishFlow
  alias IdeWeb.WorkspaceLive.ResourcesFlow

  @type flow_status :: :idle | :running | :ok | :error | atom() | nil
  @type bootstrap_status :: :idle | :starting | :running | :failed | atom() | String.t() | nil
  @type settings_pane :: :settings | :settings_store | :settings_github | atom()
  @type phoenix_form :: Phoenix.HTML.Form.t()
  @type screenshot_group :: PublishFlow.screenshot_group()
  @type github_repo_status :: Repositories.repo_status() | atom()

  @type t :: %{
          required(:pane) => atom(),
          required(:live_action) => atom(),
          optional(:project) => Project.t() | nil,
          optional(:page_title) => String.t(),
          optional(:flash) => LiveViewAssigns.flash(),
          optional(:auth_mode) => Auth.auth_mode(),
          optional(:current_user) => User.t() | nil,
          optional(:firebase_id_token) => String.t() | nil,
          optional(:firebase_id_token_exp) => integer() | nil,
          optional(:firebase_config) => AuthTypes.firebase_config(),
          optional(:debug_mode) => boolean(),
          optional(:companion_app_present) => boolean(),
          optional(:auto_format_on_save) => boolean(),
          optional(:formatter_backend) => Settings.formatter_backend(),
          optional(:tree) => FileTypes.source_tree(),
          optional(:tabs) => [EditorTypes.tab()],
          optional(:active_tab_id) => String.t() | nil,
          optional(:opening_file_id) => String.t() | nil,
          optional(:opening_file_label) => String.t() | nil,
          optional(:file_open_token) => EditorTypes.async_token(),
          optional(:expanded_tree_dirs) => MapSet.t(),
          optional(:editor_mode) => atom(),
          optional(:editor_theme) => atom(),
          optional(:editor_line_numbers) => boolean(),
          optional(:editor_active_line_highlight) => boolean(),
          optional(:editor_docs_panel_open) => boolean(),
          optional(:editor_docs_col_px) => non_neg_integer(),
          optional(:editor_doc_packages) => [CompletionTypes.doc_package_row()],
          optional(:editor_doc_package) => String.t() | nil,
          optional(:editor_doc_module) => String.t(),
          optional(:editor_doc_html) => String.t(),
          optional(:editor_doc_query) => String.t(),
          optional(:editor_context_menu) => EditorTypes.context_menu_state() | nil,
          optional(:editor_check_status) => flow_status(),
          optional(:editor_check_output) => String.t() | nil,
          optional(:editor_check_diagnostics) => [Compiler.diagnostic()],
          optional(:editor_inline_diagnostics) => [Compiler.diagnostic()],
          optional(:active_diagnostic_index) => non_neg_integer() | nil,
          optional(:editor_check_token) => EditorTypes.async_token(),
          optional(:editor_check_source_root) => String.t() | nil,
          optional(:editor_check_rel_path) => String.t() | nil,
          optional(:editor_deps_panel_open) => boolean(),
          optional(:editor_deps_usage_refresh_token) => EditorTypes.async_token(),
          optional(:editor_deps_docs_refresh_token) => EditorTypes.async_token(),
          optional(:editor_parser_panel) => boolean(),
          optional(:editor_parser_payload) => EditorTypes.parser_payload(),
          optional(:editor_tokenizer_mode) => atom(),
          optional(:editor_tokens) => [EditorTypes.tokenizer_token()],
          optional(:editor_fold_ranges) => [EditorTypes.fold_range()],
          optional(:editor_line_count) => pos_integer(),
          optional(:editor_token_diag_by_line) => EditorTypes.diagnostics_by_line(),
          optional(:tokenizer_mode) => atom(),
          optional(:token_summary) => EditorTypes.token_summary() | nil,
          optional(:token_diagnostics) => [Compiler.diagnostic()],
          optional(:token_tokens) => [EditorTypes.tokenizer_token()],
          optional(:token_diag_by_line) => EditorTypes.diagnostics_by_line(),
          optional(:formatter_parser_payload) => EditorTypes.parser_payload(),
          optional(:format_status) => flow_status(),
          optional(:format_output) => String.t() | nil,
          optional(:auto_format_last_result) => Compiler.diagnostic() | nil,
          optional(:create_file_modal_open) => boolean(),
          optional(:create_file_source_roots) => [String.t()],
          optional(:rename_file_modal_open) => boolean(),
          optional(:new_file_form) => phoenix_form(),
          optional(:rename_form) => phoenix_form(),
          optional(:package_doc_index) => CompletionTypes.package_doc_index(),
          optional(:check_status) => flow_status(),
          optional(:check_output) => String.t() | nil,
          optional(:compile_status) => flow_status(),
          optional(:compile_output) => String.t() | nil,
          optional(:manifest_status) => flow_status(),
          optional(:manifest_output) => String.t() | nil,
          optional(:build_status) => flow_status(),
          optional(:build_output) => String.t() | nil,
          optional(:build_issues) => [BuildFlow.build_issue()],
          optional(:manifest_strict_mode) => boolean(),
          optional(:debugger_state) => DebuggerTypes.runtime_state() | nil,
          optional(:debugger_rows) => [SupportTypes.debugger_row()],
          optional(:debugger_selected_row) => SupportTypes.debugger_row() | nil,
          optional(:debugger_cursor_seq) => non_neg_integer() | nil,
          optional(:debugger_timeline_mode) => String.t(),
          optional(:debugger_bootstrap_status) => bootstrap_status(),
          optional(:debugger_bootstrap_progress) => String.t() | nil,
          optional(:debugger_bootstrap_token) => pos_integer() | nil,
          optional(:debugger_companion_bootstrap_status) => bootstrap_status(),
          optional(:debugger_companion_bootstrap_progress) => String.t() | nil,
          optional(:debugger_watch_runtime) => SupportTypes.execution_model(),
          optional(:debugger_companion_runtime) => SupportTypes.execution_model(),
          optional(:debugger_watch_view_runtime) => SupportTypes.execution_model(),
          optional(:debugger_watch_trigger_buttons) => [SupportTypes.trigger_button_row()],
          optional(:debugger_companion_trigger_buttons) => [SupportTypes.trigger_button_row()],
          optional(:debugger_trigger_buttons) => [SupportTypes.trigger_button_row()],
          optional(:debugger_auto_fire_subscriptions) => [FlowTypes.auto_fire_subscription_row()],
          optional(:debugger_disabled_subscriptions) => [DebuggerTypes.disabled_subscription()],
          optional(:debugger_configuration_draft_values) => CompanionConfiguration.draft_values(),
          optional(:debugger_hovered_rendered_scope) => String.t() | nil,
          optional(:debugger_hovered_rendered_path) => String.t() | nil,
          optional(:debugger_trigger_modal_open) => boolean(),
          optional(:debugger_trigger_form) => phoenix_form(),
          optional(:debugger_speaker_effect) => DebuggerTypes.speaker_effect() | nil,
          optional(:debugger_auto_fire_refresh_scheduled) => boolean(),
          optional(:debugger_event_limit) => pos_integer(),
          optional(:debugger_since_seq) => non_neg_integer() | nil,
          optional(:debugger_types) => [String.t()],
          optional(:debugger_follow_latest) => boolean(),
          optional(:debugger_cursor_watch_runtime) => SupportTypes.execution_model() | nil,
          optional(:debugger_cursor_companion_runtime) => SupportTypes.execution_model() | nil,
          optional(:debugger_cursor_phone_runtime) => SupportTypes.execution_model() | nil,
          optional(:debugger_watch_auto_fire) => boolean(),
          optional(:debugger_companion_auto_fire) => boolean(),
          optional(:debugger_runtime_refresh_ref) => reference() | nil,
          optional(:debugger_runtime_refresh_seq) => non_neg_integer(),
          optional(:debugger_runtime_pubsub_topic) => String.t() | nil,
          optional(:emulator_targets) => [{String.t(), String.t()}],
          optional(:selected_emulator_target) => String.t(),
          optional(:emulator_mode) => String.t(),
          optional(:emulator_mode_options) => [{String.t(), String.t()}],
          optional(:emulator_form) => phoenix_form(),
          optional(:emulator_installation_status) => EmulatorTypes.installation_status(),
          optional(:emulator_dependency_install_status) => flow_status(),
          optional(:emulator_dependency_install_output) => String.t() | nil,
          optional(:pebble_build_status) => flow_status(),
          optional(:pebble_build_output) => String.t() | nil,
          optional(:pebble_install_status) => flow_status(),
          optional(:pebble_install_output) => String.t() | nil,
          optional(:emulator_stop_status) => flow_status(),
          optional(:emulator_stop_output) => String.t() | nil,
          optional(:external_emulator_running) => boolean(),
          optional(:screenshot_status) => flow_status(),
          optional(:screenshot_output) => String.t() | nil,
          optional(:capture_all_status) => flow_status(),
          optional(:capture_all_output) => String.t() | nil,
          optional(:capture_all_progress) => String.t() | nil,
          optional(:capture_all_progress_lines) => [String.t()],
          optional(:capture_all_target_statuses) => %{String.t() => String.t()},
          optional(:capture_all_token) => pos_integer() | nil,
          optional(:screenshots) => [Screenshots.screenshot()],
          optional(:screenshot_groups) => [screenshot_group()],
          optional(:publish_status) => flow_status(),
          optional(:publish_output) => String.t() | nil,
          optional(:publish_artifact_path) => String.t() | nil,
          optional(:publish_app_root) => String.t() | nil,
          optional(:publish_readiness) => [PublishReadiness.screenshot_readiness()],
          optional(:publish_checks) => [PublishReadiness.readiness_check()],
          optional(:publish_summary) => PublishFlow.publish_summary(),
          optional(:publish_warnings) => [PublishFlow.publish_warning()],
          optional(:publish_type_guidance) => PublishFlow.publish_type_guidance(),
          optional(:publish_submit_status) => flow_status(),
          optional(:publish_submit_output) => String.t() | nil,
          optional(:publish_submit_options) => PublishFlow.publish_submit_option_map(),
          optional(:publish_metrics) => PublishFlow.publish_metrics(),
          optional(:prepare_release_status) => flow_status(),
          optional(:prepare_release_output) => String.t() | nil,
          optional(:manifest_export_status) => flow_status(),
          optional(:manifest_export_output) => String.t() | nil,
          optional(:manifest_export_path) => String.t() | nil,
          optional(:release_notes_status) => flow_status(),
          optional(:release_notes_output) => String.t() | nil,
          optional(:release_notes_path) => String.t() | nil,
          optional(:release_summary) => PublishFlow.release_summary(),
          optional(:release_summary_form) => phoenix_form(),
          optional(:packages_query) => String.t(),
          optional(:packages_search_results) => [PackageTypes.search_entry()],
          optional(:packages_search_total) => non_neg_integer(),
          optional(:packages_search_busy) => boolean(),
          optional(:packages_search_progress) => String.t() | nil,
          optional(:packages_search_token) => pos_integer() | nil,
          optional(:packages_inspect_loading) => String.t() | nil,
          optional(:packages_selected) => String.t() | nil,
          optional(:packages_details) => PackageTypes.search_entry() | PackageTypes.package_details() | nil,
          optional(:packages_versions) => [String.t()],
          optional(:packages_readme) => String.t() | nil,
          optional(:packages_preview) => PackageTypes.package_preview_add() | nil,
          optional(:packages_target_root) => String.t(),
          optional(:packages_last_add_result) => PackageTypes.package_add_to_project_result() | nil,
          optional(:packages_dep_docs_package) => String.t() | nil,
          optional(:packages_dep_docs_version) => String.t() | nil,
          optional(:packages_dep_readme) => String.t() | nil,
          optional(:project_elm_direct) => [EditorDependencies.dependency_row()],
          optional(:project_elm_indirect) => [EditorDependencies.dependency_row()],
          optional(:resource_view) => String.t(),
          optional(:bitmap_resources) => [ResourceTypes.bitmap_entry()],
          optional(:bitmap_resources_error) => String.t() | nil,
          optional(:bitmap_upload_output) => String.t() | nil,
          optional(:vector_resources) => [ResourceTypes.vector_entry()],
          optional(:filtered_vectors) => [ResourceTypes.vector_entry()],
          optional(:vector_upload_output) => String.t() | nil,
          optional(:animation_resources) => [ResourceTypes.animation_resource_entry()],
          optional(:animation_upload_output) => String.t() | nil,
          optional(:font_resources) => [ResourceTypes.font_entry()],
          optional(:font_sources) => [ResourceTypes.font_source()],
          optional(:font_upload_output) => String.t() | nil,
          optional(:speaker_samples) => [ResourcesFlow.speaker_sample_row()],
          optional(:speaker_sample_upload_output) => String.t() | nil,
          optional(:project_settings_form) => phoenix_form(),
          optional(:detected_capabilities) => [String.t()],
          optional(:store_assets) => StoreAssets.status_map(),
          optional(:store_listing_sync_status) => flow_status(),
          optional(:store_listing_sync_output) => String.t() | nil,
          optional(:pending_store_listing_sync) => ProjectSettingsFlow.pending_store_listing_sync() | nil,
          optional(:github_connected?) => boolean(),
          optional(:github_repo_status) => github_repo_status(),
          optional(:github_create_status) => flow_status(),
          optional(:github_push_status) => flow_status(),
          optional(:github_push_output) => String.t() | nil,
          optional(:uploads) => LiveViewAssigns.uploads(),
          optional(:diagnostics) => [Compiler.diagnostic()],
          optional(:myself) => %Phoenix.LiveComponent.CID{cid: pos_integer()} | nil
        }
end
